# Generated by Django 3.2.4 on 2021-06-04 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0002_alter_tarefabd_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefabd',
            old_name='contents',
            new_name='content',
        ),
    ]
